In [17]:
import numpy as np

### simple_im2col関数
out_h:出力画像の高さ  
out_w:出力画像の幅(simple_im2colの出力ではないことに注意)  
cols:出力される行列  

In [18]:
def simple_im2col(img, flt_h, flt_w):
    img_h, img_w = img.shape
    out_h = img_h - flt_h + 1 
    out_w = img_w - flt_w + 1 
    cols = np.zeros((flt_h*flt_w, out_h*out_w))
    
    for h in range(out_h):
        h_lim = h + flt_h
        for w in range(out_w):
            w_lim = w + flt_w
            cols[:, h*out_w+w] = img[h:h_lim, w:w_lim].reshape(-1)
    return cols

In [19]:
img = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
cols = simple_im2col(img, 2, 2)
print(cols)

[[ 1.  2.  3.  5.  6.  7.  9. 10. 11.]
 [ 2.  3.  4.  6.  7.  8. 10. 11. 12.]
 [ 5.  6.  7.  9. 10. 11. 13. 14. 15.]
 [ 6.  7.  8. 10. 11. 12. 14. 15. 16.]]


### im2col関数
// :切り捨て除算  
out_h:出力画像の高さ  
out_w:出力画像の幅(im2colの出力ではないことに注意)  
cols:出力される行列  

In [20]:
def im2col(images, flt_h, flt_w, stride, pad):
    n_bt, n_ch, img_h, img_w = images.shape
    out_h = (img_h - flt_h + 2*pad) // stride + 1
    out_w = (img_w - flt_w + 2*pad) // stride + 1
    img_pad = np.pad(images, [(0,0), (0,0), (pad,pad), (pad,pad)], "constant") 
    cols = np.zeros((n_bt, n_ch, flt_h, flt_w, out_h, out_w))
    for h in range(flt_h):
        h_lim = h + stride*out_h
        for w in range(flt_w):
            w_lim = w + stride*out_w
            cols[:, :, h, w, :, :] = img_pad[:, :, h:h_lim:stride, w:w_lim:stride]
    
    cols = cols.transpose(1, 2, 3, 0, 4, 5).reshape(n_ch*flt_h*flt_w, n_bt*out_h*out_w)
    return cols

In [21]:
img = np.array([[[[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]]]])
cols = im2col(img, 2, 2, 1, 0)
print(cols)

[[ 1.  2.  3.  5.  6.  7.  9. 10. 11.]
 [ 2.  3.  4.  6.  7.  8. 10. 11. 12.]
 [ 5.  6.  7.  9. 10. 11. 13. 14. 15.]
 [ 6.  7.  8. 10. 11. 12. 14. 15. 16.]]
